plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
    id("com.google.devtools.ksp")
}

android {
    namespace = "com.lofipod.app"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.lofipod.app"
        minSdk = 28          // Android 9+; GrapheneOS targets recent versions
        targetSdk = 34
        versionCode = 2
        versionName = "0.2.0"
    }

    /**
     * Stable, repo-tracked signing key. Without this, every machine produces an
     * APK signed with its own auto-generated `~/.android/debug.keystore` — and
     * Android refuses to update an installed APK with a different signing cert,
     * which is what forces "uninstall before updating".
     *
     * Two-phase rollout: the keystore file is generated by running
     * `app/generate-keystore.sh` once (TODO target ~2026-05-16, see BUILD_LOG).
     * Until that file exists in the working tree, this block is a no-op and
     * the build falls back to AGP's default debug signing — so the project
     * keeps building cleanly during the gap. Once the keystore is committed,
     * every build (debug + release) signs with it and updates install in
     * place over previous versions, preserving the Room DB + DataStore.
     */
    val stableKeystore = file("lofipod-dev.jks")
    val hasStableKeystore = stableKeystore.exists()
    if (hasStableKeystore) {
        signingConfigs {
            create("lofipodDev") {
                storeFile = stableKeystore
                storePassword = "lofipod"
                keyAlias = "lofipod"
                keyPassword = "lofipod"
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            if (hasStableKeystore) {
                signingConfig = signingConfigs.getByName("lofipodDev")
            }
        }
        debug {
            isMinifyEnabled = false
            if (hasStableKeystore) {
                signingConfig = signingConfigs.getByName("lofipodDev")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    // --- Compose & lifecycle ---
    val composeBom = platform("androidx.compose:compose-bom:2024.09.02")
    implementation(composeBom)
    implementation("androidx.activity:activity-compose:1.9.2")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.navigation:navigation-compose:2.8.1")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.6")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.6")
    debugImplementation("androidx.compose.ui:ui-tooling")

    // --- Media3 (ExoPlayer) ---
    val media3 = "1.4.1"
    implementation("androidx.media3:media3-exoplayer:$media3")
    implementation("androidx.media3:media3-session:$media3")
    implementation("androidx.media3:media3-ui:$media3")
    implementation("androidx.media3:media3-common:$media3")
    implementation("androidx.media3:media3-datasource-okhttp:$media3")

    // --- Networking ---
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    // --- Room (favorites, ratings, playback positions, episode cache) ---
    val room = "2.6.1"
    implementation("androidx.room:room-runtime:$room")
    implementation("androidx.room:room-ktx:$room")
    ksp("androidx.room:room-compiler:$room")

    // --- DataStore (settings, EQ presets) ---
    implementation("androidx.datastore:datastore-preferences:1.1.1")

    // --- Coroutines ---
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")

    // --- Image loading (artwork) ---
    implementation("io.coil-kt:coil-compose:2.7.0")

    // --- Documentfile for SAF helpers ---
    implementation("androidx.documentfile:documentfile:1.0.1")
}
